### ISSUE TITLE
Ошибка в Wiki.

### ISSUE THREAD

**Issue by karkar47** [BlopSoft/OneCT#7]
В инструкции к API OneConnect, в разделе user и подразделе profile находится орфографическая ошибка. Просьба исправить.
![image](https://github.com/user-attachments/assets/7871b4fb-eff7-4913-aec7-bf44439b7d81)

**Comment by dibof228** [comment]
Не орфографическая ошибка, а просто промазываю по клавишам

**Comment by dibof228** [comment]
Исправлено

**Comment by karkar47** [comment]
сэнк ю вери мач
